### ISSUE TITLE
Headers in the tracklist

### ISSUE THREAD

**Issue by Fivda** [vgmdb/tracker#498] opened 2022-03-11 10:12 UTC
Probably to be merged within the project of individual track credits, but it would be nice to have headers to seperate categories within tracklists for albums containing different kinds of headers like "arrange/original version" or different products merged altogether for compilation discs.
Example: https://vgmdb.net/album/3097 / https://vgmdb.net/album/2032

**Comment by nstz0** [comment] 2022-03-11 13:46
Duplicate of #232

**Closed as completed by nstz0** 2022-03-11 13:46 UTC

**Comment by Fivda** [comment] 2022-03-11 13:58
> Duplicate of #232

not really, your idea seems to only be related to the title of each disc, i'm talking about something within the discs themselves
![image](https://user-images.githubusercontent.com/53372693/157881668-7627221e-ceb5-4f29-8387-620424fa64e7.png)

**Comment by nstz0** [comment] 2022-03-11 14:02
Nope, it's talking about titles within a disc. You should check the examples.

**Comment by Fivda** [comment] 2022-03-11 14:04
I did, but they were all DVDs for the most part so i thought you were just talking about giving titles to the media types themselves rather than full fledged sections
