### ISSUE TITLE
Adding tracks to an exist tracklist won't show in album's edit history (albums-history.php)

### ISSUE THREAD

**Issue by xian2xian2** [vgmdb/tracker#493] opened 2022-02-28 06:09 UTC
But it will show as an edit in recently updates (recent.php) and trigger an archive.

[PCCG-02123](https://vgmdb.net/album/116779), edited in Jan 27th, captured in Jan 28th. Times are GMT+8.
Comments of adding the track (Group #70779) just disappeared.
![屏幕截图 2022-01-28 011422](https://user-images.githubusercontent.com/12865009/155931832-e6606899-5a7f-46ca-ad0a-428535ac4d99.jpg)
![屏幕截图 2022-01-28 011442](https://user-images.githubusercontent.com/12865009/155931835-4c276f9c-60a1-4d47-b2c8-6e544c37c223.jpg)

**Comment by nstz0** [comment] 2022-03-03 21:53
Duplicate of #453

**Closed as completed by nstz0** 2022-03-03 21:53 UTC
