### ISSUE TITLE
Prevent duplicate submission

### ISSUE THREAD

**Issue by Fivda** [vgmdb/tracker#150] opened 2021-01-19 11:05 UTC
Some form of anti-duplicate submission prevention would be good: Maybe if a submission is detected and deemed identical to one submitted less than 5 seconds ago (accidental double clicking, etc), it would send a warning or stop the submission?

**Comment by Illidanz** [comment] 2021-01-19 11:06
Duplicate of #2

**Closed as completed by Illidanz** 2021-01-19 11:06 UTC
Labels: enhancement, web
